Input/Output Streams
dgrimaliuc/training_for_mirela pull request #2
Opened 2023-01-12 21:59 UTC by MirelaBoaghe

2023-01-13 15:57 UTC, dgrimaliuc-crunchyroll requested changes

2023-01-13 15:57 UTC, dgrimaliuc-crunchyroll commented on trainging_for_mirela/src/main/java/exceptions/task1/FileReader.java
> +            data = new String(Files.readAllBytes(Paths.get(fileName)));
the task was to use FileInputStream() a d FileOutputStream()
it is a different way

2023-01-13 15:58 UTC, dgrimaliuc-crunchyroll commented
This PR contains to many files which are not related to Input Output stream task
Please commit then in master, only i/o task should remain

2023-01-13 16:17 UTC, dgrimaliuc-crunchyroll requested changes

2023-01-13 16:17 UTC, dgrimaliuc-crunchyroll commented on trainging_for_mirela/src/main/java/time/Time.java
> -//    public static boolean secondCheck(int second) {
please don't keep commented code 
or remove it or uncomment

2023-01-13 16:17 UTC, dgrimaliuc-crunchyroll commented on trainging_for_mirela/src/main/java/input_output_streams/MainInputOutputFiles.java
> +    public static void writeReversedContentInOutputFile(File fileName) {
it is not logical to have fileName parameter of Type File

2023-01-13 16:17 UTC, dgrimaliuc-crunchyroll commented on trainging_for_mirela/src/main/java/input_output_streams/MainInputOutputFiles.java
> +        stringBuilder.append(information).reverse();
make it easier

2023-01-13 16:17 UTC, dgrimaliuc-crunchyroll commented on trainging_for_mirela/src/main/java/input_output_streams/MainInputOutputFiles.java
> +        fileContents = String.valueOf(stringBuilder);
make it easier

2023-01-13 16:17 UTC, dgrimaliuc-crunchyroll commented on trainging_for_mirela/src/main/java/input_output_streams/MainInputOutputFiles.java
> +            file.close();
so if an exceptions will appear in 114-117 strings resource will not be closed ?

2023-01-13 16:17 UTC, dgrimaliuc-crunchyroll commented on trainging_for_mirela/src/main/java/input_output_streams/MainInputOutputFiles.java
> +    public static void readContentsBufferedReader(File fileName) {
it is not logical to have fileName parameter of Type File

2023-01-13 16:17 UTC, dgrimaliuc-crunchyroll commented on trainging_for_mirela/src/main/java/input_output_streams/MainInputOutputFiles.java
> +    public static void readContentsBufferedReader(File fileName) {
the method name is too long and unclear

2023-01-13 16:17 UTC, dgrimaliuc-crunchyroll commented on trainging_for_mirela/src/main/java/input_output_streams/MainInputOutputFiles.java
> +                stringBuilder.append(line + System.lineSeparator());
why System.lineSeparator() ?
if I enter an line separator from console file will have two System.lineSeparator() ?

2023-01-13 16:17 UTC, dgrimaliuc-crunchyroll commented on trainging_for_mirela/src/main/java/input_output_streams/MainInputOutputFiles.java
> +            input.close();
so if an exceptions will appear in 114-117 strings resource will not be closed ?

2023-01-13 16:17 UTC, dgrimaliuc-crunchyroll commented on trainging_for_mirela/src/main/java/input_output_streams/MainInputOutputFiles.java
> +        try (FileInputStream file = new FileInputStream(fileName);
why this method contains FileInputStream ?

2023-01-13 16:17 UTC, dgrimaliuc-crunchyroll commented on trainging_for_mirela/src/main/java/input_output_streams/MainInputOutputFiles.java
> +            byte[] dataBytes = data.getBytes();
don't use byte array, there is an other way to read all bytes

2023-01-13 16:17 UTC, dgrimaliuc-crunchyroll commented on trainging_for_mirela/src/main/java/input_output_streams/MainInputOutputFiles.java
> +            file.close();
not here

2023-01-13 16:17 UTC, dgrimaliuc-crunchyroll commented on trainging_for_mirela/src/main/java/input_output_streams/MainInputOutputFiles.java
> +        String data = "Hello World!";
Why is it here?

2023-01-13 16:17 UTC, dgrimaliuc-crunchyroll commented on trainging_for_mirela/src/main/java/input_output_streams/MainInputOutputFiles.java
> +            if (createdFile.createNewFile()) {
createNewFile() throws IOException 
if it will be thrown FileCreationExeption() will not be triggered 
not exactly what task requires

2023-01-13 16:17 UTC, dgrimaliuc-crunchyroll commented on trainging_for_mirela/src/main/java/input_output_streams/MainInputOutputFiles.java
> +    public static File createInputFile(String fileName) {
so you have two methods for creating a file ?

2023-01-13 16:17 UTC, dgrimaliuc-crunchyroll commented on trainging_for_mirela/src/main/java/input_output_streams/MainInputOutputFiles.java
> +        writeInformationIntoTheFile(inputFile);
hmm, should you first of all require user to enter a string from console ?

2023-01-13 16:17 UTC, dgrimaliuc-crunchyroll commented on trainging_for_mirela/src/main/java/input_output_streams/MainInputOutputFiles.java
> +            throw new RuntimeException(e);
you have to catch it inside readFileName()

2023-01-13 16:17 UTC, dgrimaliuc-crunchyroll commented on trainging_for_mirela/src/main/java/input_output_streams/MainInputOutputFiles.java
> +    public static String readFileName() throws IOException {
should not throw an exception

2023-01-13 16:17 UTC, dgrimaliuc-crunchyroll commented on trainging_for_mirela/src/main/java/input_output_streams/MainInputOutputFiles.java
> +        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
can you create an method for reading a string from user ?

2023-01-13 16:17 UTC, dgrimaliuc-crunchyroll commented on trainging_for_mirela/src/main/java/input_output_streams/MainInputOutputFiles.java
> +             BufferedReader input = new BufferedReader(new InputStreamReader(file));) {
Task didn't require something like that

2023-01-13 16:17 UTC, dgrimaliuc-crunchyroll commented on trainging_for_mirela/src/main/java/input_output_streams/MainInputOutputFiles.java
> +            OutputStream file = new FileOutputStream(fileName);
probably will not be closed

2023-01-13 16:19 UTC, dgrimaliuc-crunchyroll commented
by the way, did you created denis-branch or used mine?
next time create your branch 
because in mine can be some important changes which I would not like to commit

2023-01-18 21:06 UTC, MirelaBoaghe commented on trainging_for_mirela/src/main/java/input_output_streams/MainInputOutputFiles.java
> +    public static File createInputFile(String fileName) {
Yes, because I have two different exeptions for input and output file, can I do it in just one method?

2023-01-26 08:22 UTC, dgrimaliuc requested changes

2023-01-26 08:22 UTC, dgrimaliuc commented on trainging_for_mirela/src/main/resources/information.txt
> +Having fun with Santa now
generated file should not be commited

2023-01-29 17:19 UTC, closed without merging